###  suggest badge

POST http://localhost:1234/api/badgesAndLevels/sendToPendingBadges/brando16
Content-Type: application/json

{
    "badge": "hiker",
    "keyword": "hike"
}


###  evaluate badge

POST http://localhost:1234/api/badgesAndLevels/evaluateBadge
Content-Type: application/json

{
    "id": 2,
    "decision": "accepted"
}

### get user and badge levels

GET http://localhost:1234/api/badgesAndLevels/getUserAndBadgeLevels

### get badges 

GET http://localhost:1234/api/badgesAndLevels/getBadges
