###  suggest badge

POST http://localhost:1234/api/badgesAndLevels/sendToPendingBadges/brando16
Content-Type: application/json

{
    "badge": "dog lover",
    "keyword": "walk"
}


###  evaluate badge

POST http://localhost:1234/api/badgesAndLevels/evaluateBadge
Content-Type: application/json

{
    "id": 3,
    "decision": "rejected"
}

### get user and badge levels

GET http://localhost:1234/api/badgesAndLevels/getUserAndBadgeLevels

### get badges 

GET http://localhost:1234/api/badgesAndLevels/getBadges
