### add habit

POST http://localhost:1234/api/habits/addHabit/leslie25
Content-Type: application/json

{
    "habit": "read a book in french",
    "deadline": "2025-01-11"
}

###  complete habit

PUT http://localhost:1234/api/habits/completeHabit/leslie25
Content-Type: application/json

{
    "habit": "read a book in french",
    "deadline": "2025-01-10"
}

###  delete habit

DELETE http://localhost:1234/api/habits/deleteHabit/leslie25
Content-Type: application/json

{
    "habit": "read a book in french",
    "deadline": "2025-01-11"
}
