### get chat

GET  http://localhost:1234/api/messages/getChat/leslie25

### send message

POST http://localhost:1234/api/messages/sendMessage/brando16
Content-Type: application/json

{
    "message": "Por qué no respondes? :("
}

### edit message

PUT http://localhost:1234/api/messages/editMessage
Content-Type: application/json

{
    "id": 1,
    "newMessage": "Hola! Bien y tú? Cómo has estado?"
}

### delete message

DELETE  http://localhost:1234/api/messages/deleteMessage
Content-Type: application/json

{
    "id": 2
}