### get user profile        
    
GET http://localhost:1234/api/profile/profile/leslie25

### get user's achievements        
    
GET http://localhost:1234/api/profile/achievements/brando16 

### send friend request

POST http://localhost:1234/api/profile/sendFriendRequest/leslie25

### get friend requests

GET http://localhost:1234/api/profile/getFriendRequests/leslie25

### get friends

GET http://localhost:1234/api/profile/getFriends/brando16

### respond to friend request

POST http://localhost:1234/api/profile/respondToFriendRequest/leslie25
Content-Type: application/json

{
    "id": 1,
    "response": "accepted"
}

