### get user profile        
    
GET http://localhost:1234/api/profile/hiran06

### get user's achievements        
    
GET http://localhost:1234/api/profile/achievements/hiran06 

### send friend request

POST http://localhost:1234/api/profile/sendFriendRequest/brando16

### get friend requests

GET http://localhost:1234/api/profile/getFriendRequests/brando16

### get friends

GET http://localhost:1234/api/profile/getFriends/brando16

### respond to friend request

POST http://localhost:1234/api/profile/respondToFriendRequest/brando16
Content-Type: application/json

{
    "id": 2,
    "response": "accepted"
}

