### get ranking in user's country        
    
GET http://localhost:1234/api/statistics/rankingInUsersCountry/brando16

### get worldwide ranking      
    
GET http://localhost:1234/api/statistics/rankingWorlWide



### get worldwide ranking for user's theme       
    
GET http://localhost:1234/api/statistics/themeWorldWideRanking/brando16

### get  ranking for user's country by theme       
    
GET http://localhost:1234/api/statistics/rankingInUsersCountryByTheme/brando16

### get habits that have been completed at least 45 times      
    
GET http://localhost:1234/api/statistics/atLeast45Completions/brando16

### get days where the habit was completed the most     
    
GET http://localhost:1234/api/statistics/mostFrequentDays/brando16
Content-Type: application/json

{
    "habit": "work out"
}
