## create user
POST http://localhost:1234/api/user/createUser
Content-Type: application/json

# {
#     "firstName": "Brando",
#     "lastName": "Hernandez",
#     "username": "brando16", 
#     "userEmail": "brandodavid16@gmail.com",
#     "theme": "greek_gods",
#     "dateOfBirth": "1994-07-16",
#     "country": "Venezuela", 
#     "password": "Leslie2505."
# }

# {
#     "firstName": "Hiran",
#     "lastName": "Hernandez",
#     "username": "hiran06", 
#     "userEmail": "hiran@gmail.com",
#     "theme": "magic",
#     "dateOfBirth": "1990-05-06",
#     "country": "Venezuela", 
#     "password": "Brando1607."
# }


{
    "firstName": "Leslie",    
    "lastName": "Caro",
    "username": "leslie25", 
    "userEmail": "leslie@gmail.com",
    "theme": "traveler",
    "dateOfBirth": "1989-05-25",
    "country": "Chile", 
    "password": "Brando1607."
}


###


### log user in

POST http://localhost:1234/api/user/login
Content-Type: application/json

{
    "login": "brando16",
    "password": "Leslie2505."
}

### logout

GET http://localhost:1234/api/user/logout

### send temporary password

POST http://localhost:1234/api/user/sendTemporaryPassword
Content-Type: application/json

{
    "username": "brando16"
}

### change password

PUT http://localhost:1234/api/user/changePassword
Content-Type: application/json

{
    "username": "brando16",
    "tempPassword": "cc5b6dccce",
    "newPassword": "Leslie2505."
}

### change username or email

PUT  http://localhost:1234/api/user/changeLogin/brando16
Content-Type: application/json

{
    "passwordToCheck": "Leslie2505.",
    "new_email": "brandodavid16@gmail.com"
}

