## add user
POST http://localhost:1234/api/user/createUser
Content-Type: application/json

# {
#     "firstName": "Brando",
#     "lastName": "Hernandez",
#     "username": "brando16", 
#     "userEmail": "brandodavid16@gmail.com",
#     "theme": "greek_gods",
#     "dateOfBirth": "1994-07-16",
#     "country": "Venezuela", 
#     "password": "Leslie2505."
# }

{
    "firstName": "Hiran",
    "lastName": "Hernandez",
    "username": "hiran06", 
    "userEmail": "hiran@gmail.com",
    "theme": "magic",
    "dateOfBirth": "1990-05-06",
    "country": "Venezuela", 
    "password": "Brando1607."
}


# {
#     "firstName": "Leslie",    
#     "lastName": "Caro",
#     "username": "leslie25", 
#     "userEmail": "leslie@gmail.com",
#     "theme": "traveler",
#     "dateOfBirth": "1989-05-25",
#     "country": "Chile", 
#     "password": "Brando1607."
# }


###


### log user in

POST http://localhost:1234/api/user/login
Content-Type: application/json

{
    "login": "brando16",
    "password": "Leslie2505."
}

### logout

GET http://localhost:1234/api/user/logout

### send temporary password

POST http://localhost:1234/api/user/sendTemporaryPassword
Content-Type: application/json

{
    "username": "brando16"
}

### change password

PUT http://localhost:1234/api/user/changePassword
Content-Type: application/json

{
    "username": "brando16",
    "tempPassword": "7207e457ee",
    "newPassword": "Leslie2505."
}

### change username or email

PUT  http://localhost:1234/api/user/changeLogin/brando16
Content-Type: application/json

{
    "passwordToCheck": "Leslie2505.",
    "new_email": "brando16@gmail.com"
}

### get user profile        
    
GET http://localhost:1234/api/user/profile/leslie25

### get user's achievements        
    
GET http://localhost:1234/api/user/achievements/brando16 

### send friend request

POST http://localhost:1234/api/user/sendFriendRequest/leslie25

### get friend requests

GET http://localhost:1234/api/user/getFriendRequests/leslie25

### get friends

GET http://localhost:1234/api/user/getFriends/brando16

### respond to friend request

POST http://localhost:1234/api/user/respondToFriendRequest/leslie25
Content-Type: application/json

{
    "id": 1,
    "response": "accepted"
}

### send message

POST http://localhost:1234/api/user/sendMessage/leslie25
Content-Type: application/json

{
    "message": "Todo bien y tú?"
}